global using System;
global using System.Linq;
global using Xunit;
global using FluentAssertions;
global using Microsoft.AspNetCore.Http;
global using System.Net.Http;
global using System.Threading.Tasks;
global using NSubstitute;
global using AutoFixture;
global using Microsoft.Extensions.Primitives;
global using System.Collections.Generic;
global using CaptainLogger.RequestTracer.Headers;
global using static CaptainLogger.RequestTracer.Globals.Constants;
