namespace CaptainLogger.Extensions.Generator.Helpers;

internal static class CodeExtensions
{
  public static string AutoGeneratedComment =>
    $"// <auto-generated last-generation=\"{DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC\" />";

  public static string BrowsableAttribute =>
    "[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Always)]";

  public static string GeneratedCodeAttribute(string? tool, string? version = null) =>
    $"[System.CodeDom.Compiler.GeneratedCodeAttribute(\"{tool}\", \"{version}\")]";

  public static string ToNullableDirectiveIfEnabled(
    this bool nullable)
  {
    return nullable ? "#nullable enable\r\n" : "";
  }

  public static string GetFormattedCode(this SyntaxNode code)
  {
    var formattedCode = code
      .NormalizeWhitespace(indentation: "  ")
      .SyntaxTree
      .GetText()
      .ToString();

    return formattedCode;
  }

  public static string GetFormattedCode(this string code)
  {
    var formattedCode = CSharpSyntaxTree
      .ParseText(code)
      .GetRoot()
      .GetFormattedCode();

    return formattedCode;
  }
}
