name: .NET

on:
  create:
    branches: 
      - release/**
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.CECCOMIL_NUGET }}
        nuget-version: '6.x'

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          10.0.x
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore ./src/CaptainLogger

    - name: Build
      run: dotnet build ./src/CaptainLogger --no-restore --configuration $env:BUILD_CONFIG

    - name: Tests
      run: dotnet test ./src/CaptainLogger/CaptainLogger.Tests /p:Configuration=$env:BUILD_CONFIG --no-restore --verbosity normal

    - name: Generator Tests
      run: dotnet test ./src/CaptainLogger/CaptainLogger.Extensions.Generator.Tests /p:Configuration=$env:BUILD_CONFIG --no-restore --verbosity normal

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v')
      run: nuget push **/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{ secrets.CECCOMIL_NUGET }} -SkipDuplicate